name: Deploy Vue + Laravel to Render

on:
  push:
    branches:
      - main  # 當 push 到 main 分支時觸發

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 檢出專案代碼
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: 設置 Node.js（Vue 构建）
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: 安裝和構建 Vue
      - name: Install and build Vue
        run: |
          cd frontend
          npm install
          npm run build
        env:
          NODE_ENV: production

      # Step 4: 設置 PHP 和 Composer（Laravel 後端）
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # Step 5: 安裝 Laravel 依賴
      - name: Install Composer dependencies
        run: |
          cd backend
          composer install --optimize-autoloader --no-dev
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # Step 6: 部署至 Render
      - name: Deploy to Render
        env:
          API_KEY: ${{ secrets.API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: |
          # Render CLI 部署命令
          render-cli deploy --service $APP_NAME --api-key $API_KEY
